apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-tcp
  namespace: argocd-system
spec:
  destination:
    namespace: apps-system
    server: https://kubernetes.default.svc
  project: apps-system
  sources:
    - ref: argocd-self
      repoURL: https://github.com/terenowe-info/helm.git
      targetRevision: main
    - helm:
        releaseName: apps-tcp
        valueFiles:
          - $argocd-self/base/apps-wrapped/tcp/values.yaml
      repoURL: https://github.com/seemscloud/helm-charts.git
      path: charts/wrapper
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: Ingress
      group: networking.k8s.io
      name: apps-tcp-external
      jsonPointers:
        - /spec/rules