apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stakater-reloader
  namespace: argocd-system
spec:
  project: stakater-reloader-system
  destination:
    server: https://kubernetes.default.svc
    namespace: stakater-reloader-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/terenowe-info/helm.git
      targetRevision: main
      ref: argocd-self
    - chart: reloader
      repoURL: https://stakater.github.io/stakater-charts
      targetRevision: 1.0.65
      helm:
        releaseName: stakater-reloader
        valueFiles:
          - $argocd-self/base/stakter-reloader/values.yaml
