fullnameOverride: "apps"

resources:
  - metadata:
      namespace: ""
      labels: { }
      annotations: { }
    resources:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: hostname
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: apps-hostname
          template:
            metadata:
              labels:
                app: apps-hostname
            spec:
              volumes:
                - name: config
                  configMap:
                    name: apps-hostname
              containers:
                - name: hostname
                  image: python:3.11-alpine3.19
                  workingDir: /app
                  volumeMounts:
                    - name: config
                      subPath: main.py
                      mountPath: /app/main.py
                  command:
                    - /bin/sh
                    - -c
                  args:
                    - |
                      pip3 install --upgrade pip
                      pip3 install uvicorn fastapi

                      mkdir -p /app

                      cd /app

                      uvicorn main:app \
                        --host 0.0.0.0 \
                        --port 8080
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: hostname
        data:
          main.py: |
            from fastapi import FastAPI, Request
            import socket

            app = FastAPI()


            @app.get("/")
            def read_root(request: Request):
                return {"address": request.client.host, "xxx":socket.gethostname()}
      - apiVersion: v1
        kind: Service
        metadata:
          name: hostname
        spec:
          selector:
            app: apps-hostname
          ports:
            - protocol: TCP
              port: 8080
              targetPort: 8080
      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: hostname
        spec:
          ingressClassName: nginx-external
          rules:
            - host: hostname.sigma.prod.terenowe.seems.cloud
              http:
                paths:
                  - backend:
                      service:
                        name: apps-hostname
                        port:
                          number: 8080
                    path: /
                    pathType: Prefix