fullnameOverride: rabbitmq

replicaCount: 1

service:
  type: LoadBalancer
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-subnet: "gke-sigma-prod-aaa-lb"
  loadBalancerIP: "10.150.150.10"

metrics:
  enabled: false
  serviceMonitor:
    enabled: true

persistence:
  enabled: true
  size: 1Gi

auth:
  username: admin
  password: "admin"
  erlangCookie: "Ih0wplVwoBGLAW0JibgNhSE97vB3Sktl"

serviceAccount:
  create: true
