fullnameOverride: "cert-manager"

resources:
  - metadata:
      namespace: ""
      labels: { }
      annotations: { }
    resources:
      - apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-prod
        spec:
          acme:
            server: https://acme-v02.api.letsencrypt.org/directory
            email: certificates@terenowe.info
            privateKeySecretRef:
              name: letsencrypt-prod
            solvers:
              - http01:
                  ingress:
                    ingressClassName: nginx
      - apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: argocd-local
        spec:
          secretName: argocd-local-tls
          issuerRef:
            name:
            kind: ClusterIssuer
            # This is optional since cert-manager will default to this value however
            # if you are using an external issuer, change this to that issuer group.
            group: cert-manager.io
