apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-external
  namespace: argocd-system
spec:
  project: nginx-ingress-system
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/terenowe-info/helm.git
      targetRevision: main
      ref: argocd-self
    - chart: nginx-ingress
      repoURL: https://helm.nginx.com/stable
      targetRevision: 1.1.0
      helm:
        releaseName: nginx-ingress-external
        valueFiles:
          - $argocd-self/base/nginx-ingress/external/values.yaml
