fullnameOverride: nginx-ingress-external

rbac:
  create: true

prometheus:
  create: true

controller:
  terminationGracePeriodSeconds: 1
  replicaCount: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  ingressClass:
    name: nginx-external
    create: true

  reportIngressStatus:
    enableLeaderElection: true
    leaderElectionLockName: "nginx-ingress-external-leader"

  containerPort:
    http: 80
    https: 443

  httpPort:
    enable: true
    port: 80
    targetPort: 80

  httpsPort:
    enable: true
    port: 443
    targetPort: 443

  service:
    create: true
    type: LoadBalancer

  config:
    entries:
      proxy_set_header Forwarded $proxy_add_forwarded;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;