apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd-system
spec:
  project: argocd-system
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/terenowe-info/helm.git
      targetRevision: main
      ref: argocd-self
    - chart: argocd-apps
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 1.4.0
      helm:
        releaseName: argocd-apps
        valueFiles:
          - $argocd-self/base/argocd/argocd-apps/values.yaml
