projects:
  - name: argocd-system
    namespace: argocd-system
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    sourceRepos:
      - 'https://github.com/seemscloud/helm-argocd-self.git'
      - 'https://argoproj.github.io/argo-helm'
      - 'https://charts.bitnami.com/bitnami'
    destinations:
      - namespace: "*"
        name: "in-cluster"
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: queues-system
    namespace: argocd-system
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    sourceRepos:
      - 'https://charts.redpanda.com/'
      - 'https://github.com/seemscloud/helm-argocd-self.git'
      - 'https://charts.bitnami.com/bitnami'
    destinations:
      - namespace: queues-system
        name: "in-cluster"
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: cert-manager-system
    namespace: argocd-system
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    sourceRepos:
      - 'https://charts.jetstack.io'
      - 'https://github.com/seemscloud/helm-argocd-self.git'
    destinations:
      - namespace: cert-manager-system
        name: "in-cluster"
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
