apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd-system
spec:
  project: argocd-system
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/terenowe-info/helm.git
      targetRevision: main
      ref: argocd-self
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.51.4
      helm:
        releaseName: argocd
        valueFiles:
          - $argocd-self/base/argocd/argocd/values.yaml
